config/routes.rb
Rails.application.routes.draw do
  
  get 'coupons/generate_coupon_code'
  get 'coupons/check_coupon_code'
  post 'check_coupon_code' => 'coupons#check_coupon_code'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  resources :users do
  resources :credit_cards
  end

  resources :users do
  resources :papers
  end
  resources :papers
  resources :receipts
  resources :conferences
  resources :conference_registrations
  resources :event_registrations
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  
  get 'select-conference' => 'conference_registrations#select_conference'
  get 'select-events' => 'conference_registrations#select_events'
  get 'registration_summary' => 'conference_registrations#registration_summary'
  post 'registration_summary' => 'conference_registrations#get_discount'
  post 'registration/final' => 'conference_registrations#final'

  root             'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup'  => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get 'credit_cards/index'
  get 'credit_cards/new'
  get 'credit_cards/create'
  get 'credit_cards/edit'
  get 'credit_cards/update'
  get 'credit_cards/show'
  get 'credit_cards/destroy'
  get 'conferences/new'
  get 'conferences/create'
  get 'conferences/edit'
  get 'conferences/update'
  get 'conferences/destroy'
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'

end

app/models/paper.rb
class Paper < ActiveRecord::Base
	has_attached_file :attachment

	validates_attachment_content_type :attachment, content_type: 'application/pdf'

  validates :title, :authors, :attachment, :user_id, presence: true

  validates_uniqueness_of :title, :scope => [:authors], message: " exists. This paper has already been added to your account."

	belongs_to :user
  
  before_save :perform_attachment_removal

	def perform_attachment_removal
		if :remove_attachment == '1' && !attachment.dirty?
      self.attachment = nil
		end
	end

end

app/controllers/papers_controller.rb
class PapersController < ApplicationController

  def index
		@papers = current_user.papers
		@user = current_user
	end

	def new
    @user = current_user
		@paper = current_user.papers.build
	end

	def create
    @user = current_user
		@paper = current_user.papers.new(paper_params)
    if @paper.save
      flash[:success] = "The new paper has been saved to your account"
      redirect_to user_papers_path(@user)
    else
      render 'papers/new'
    end
	end

	def edit
    @paper = current_user.papers.find(params[:id])
    @user = current_user
  end

  def update
    @paper = current_user.papers.find(params[:id])
    if @paper.update(paper_params)
      flash[:success] = "Your paper has been successfully updated"
      redirect_to user_papers_path
    else
      render 'edit'
    end
  end

  def destroy
    current_user.papers.find(params[:id]).destroy
    flash[:success] = "Paper deleted"
    redirect_to user_papers_path
  end

	private
  def paper_params
    params.require(:paper).permit(:title, :authors, :attachment, :remove_attachment)
  end

end

app/views/papers/edit.html.erb
<% provide(:title, 'Edit Paper') %>
<h1>Edit this paper</h1>
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= form_for(@paper, url: user_paper_path, method: :patch, :html => { :multipart => true }) do |paper| %>
		<% if @paper.errors.any? %>
		<div id="error_explanation">
			<h2>
				<%= pluralize(@paper.errors.count, "error") %> prohibited
				this paper from being saved:
			</h2>
			<ul>
				<% @paper.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
		<% end %>
		<%= paper.label :title %>
		<%= paper.text_field :title %>
		<%= paper.label :authors %>
		<%= paper.text_field :authors %>
		<% if paper.object.attachment? %>
	  <table class="table table-bordered table-striped">
	    <tr>
	      <td><%= label_tag("Current Paper") %></td>
	      <td><%= link_to paper.object.title, paper.object.attachment.url %></td>
	    </tr>
	    <tr>
	      <td><%= label_tag :remove_attachment, "Remove paper?" %></td>
	      <td><%= check_box_tag :remove_attachment%></td>
	    </tr>
	    </table>
		<% end %>
		<%= paper.file_field :attachment %>

		<%= paper.submit "Update", class: "btn btn-primary" %>
		<% end %>
		<br>
		<p class="text-center"><%= link_to 'Return to your dashboard', user_path(@user) %></p>
	</div>
</div>

app/views/papers/index.html.erb
<% provide(:title, 'View All Papers') %>
<h1>Your papers</h1>
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<% if  !@papers.empty? %>
		<table class="table table-bordered table-striped">
			<tr>
				<th>Name</th>
				<th>Authors</th>
				<th>Attachment</th>
				<th>Edit</th>
				<th>Delete</th>
			</tr>
			<% @papers.each do |paper| %>
			<tr>
				<td><%= paper.title %></td>
				<td><%= paper.authors %></td>
				<td>
					<% if paper && paper.attachment? %>
					<span class="label label-info">Attachment</span>
					<%= link_to paper.title, paper.attachment.url %>
					<% end %>
				</td>
				<td><%= link_to 'Edit', edit_user_paper_path(@user, paper) %></td>
				<td><%= link_to 'Delete', user_paper_path(@user, paper),
					method: :delete,
					data: { confirm: 'Are you sure?' } %></td>
				</tr>
				<% end %>
			</table>
			<p class="text-center"><%= link_to 'Return to your dashboard', user_path(@user) %></p>
			<% else %>
			<h2>It looks like you haven't added any papers...yet!</h2>
			<p class="text-center"><%= link_to 'Upload a new paper', new_user_paper_path(@user) %></p>
			<p class="text-center"><%= link_to 'Return to your dashboard', user_path(@user) %></p>
			<% end %>
		</div>
	</div>

app/views/papers/new.html.erb
<% provide(:title, 'Add Paper') %>
<h1>Add a paper</h1>
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= form_for([@user, @paper], :url => user_papers_path, method: :post, :html => { :multipart => true }) do |paper| %>
		<% if @paper.errors.any? %>
		<div id="error_explanation">
			<h2>
				<%= pluralize(@paper.errors.count, "error") %> prohibited
				this paper from being saved:
			</h2>
			<ul>
				<% @paper.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
		<% end %>
		<%= paper.label :title %>
		<%= paper.text_field :title %>
		<%= paper.label "Author(s)" %>
		<%= paper.text_field :authors %>
		<%= paper.label "Attachment (must be in PDF form)" %>
		<%= paper.file_field :attachment %>
		<%= paper.submit "Add", class: "btn btn-primary" %>
		<% end %>
		<br>
		<p class="text-center"><%= link_to 'Return to your dashboard', user_path(@user) %></p>
	</div>
</div>