config/routes.rb
Rails.application.routes.draw do
  
  get 'coupons/generate_coupon_code'
  get 'coupons/check_coupon_code'
  post 'check_coupon_code' => 'coupons#check_coupon_code'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  resources :users do
  resources :credit_cards
  end

  resources :users do
  resources :papers
  end
  resources :papers
  resources :receipts
  resources :conferences
  resources :conference_registrations
  resources :event_registrations
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  
  get 'select-conference' => 'conference_registrations#select_conference'
  get 'select-events' => 'conference_registrations#select_events'
  get 'registration_summary' => 'conference_registrations#registration_summary'
  post 'registration_summary' => 'conference_registrations#get_discount'
  post 'registration/final' => 'conference_registrations#final'

  root             'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup'  => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get 'credit_cards/index'
  get 'credit_cards/new'
  get 'credit_cards/create'
  get 'credit_cards/edit'
  get 'credit_cards/update'
  get 'credit_cards/show'
  get 'credit_cards/destroy'
  get 'conferences/new'
  get 'conferences/create'
  get 'conferences/edit'
  get 'conferences/update'
  get 'conferences/destroy'
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'

end

app/models/conference_registration.rb
class ConferenceRegistration < ActiveRecord::Base
  validates :user_id, :conference_id, :diet, :name, :email, presence: true

  validates_uniqueness_of :user_id, :scope => [:name, :email, :conference_id, :paper_id], message: " cannot register the same paper for the same conference twice."

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX }

  belongs_to :user
  belongs_to :conference
end

app/controllers/conference_registrations_controller.rb
class ConferenceRegistrationsController < ApplicationController
  skip_before_filter :verify_authenticity_token
	
	@@discount = 0

	def index
		@user = current_user
		@user_registrations = current_user.conference_registrations
	end

	def select_conference
		@conferences = Conference.all
	end

	def select_events
		@conference = Conference.find(params[:conference_id])
		@events = @conference.events
	end

	def new
		@user = current_user
		@papers = current_user.papers
		@conference = Conference.find(params[:conference_id])
		@conf_reg = ConferenceRegistration.new
		if params[:events]
			session[:events] ||= []
			session[:events] = params[:events]
			@events = session[:events]
		else
			session[:events] = 0 
		end
	end 

	def create
		@conf_reg = ConferenceRegistration.new(registration_params)
		if params[:paper_id]
			@conf_reg.paper_id = params[:paper_id]
		else
			@conf_reg.paper_id = nil
		end 
		session[:tmp_conf_reg] = @conf_reg
		redirect_to action: :registration_summary
	end

	def get_discount
		if params[:discount]
			@@discount = params[:discount]
		end
		redirect_to action: :registration_summary
	end

	def registration_summary
		@user = current_user
		# Retrieve selected conference registration details.
	  @conf_reg = session[:tmp_conf_reg]
		@conference = Conference.find_by(id: @conf_reg["conference_id"])
		
		# Initialize new coupon.
		@coupon = Coupon.new
    
    # Initialize fees.
    @fee = @conference.fee
		@event_fees = 0
		@paper_fee = 0
   

    # If event was selected...
		@events = session[:events]
		if @events != 0
			@events.each do |event|
				event = Event.find_by(id: event.to_i)
				@event_fees = @event_fees + event.fee
			end
		end

		# If paper was selected...
		@paper_id = @conf_reg["paper_id"]
		if @paper_id != nil
			@paper = Paper.find_by(id: @paper_id)
		  @paper_fee = @conference.paper_fee
		end
		
		@total = @fee + @paper_fee + @event_fees

		@cards = current_user.credit_cards
	end

	def final
		@conference = Conference.find_by(id: session[:tmp_conf_reg]["conference_id"])
		
    # Initialize fees and discounts.
    @discount = @@discount.to_d
		@fee = @conference.fee
		@paper_fee = 0
		@event_fees = 0
		
    # If events where selected...
		@events = session[:events]
		@event_regs = Array.new
		if @events != 0
		  @events.each do |event|
			  event = Event.find_by(id: event.to_i)
			  @event_fees = @event_fees + event.fee
			  @event_reg = EventRegistration.new({:user_id => current_user.id, :event_id => event.id})
			  @event_reg.save
			  @event_regs << @event_reg	
		  end
		end
    
    # Save conference registration.
		@conf_reg = ConferenceRegistration.new(session[:tmp_conf_reg])
		
		if @conf_reg.save

    # If a paper was selected...
    @paper_id = @conf_reg.paper_id
    if @paper_id != nil
    	@paper_fee = @conference.paper_fee
    end
		
		# Calculate subtotal.
		@sub_total = @fee + @paper_fee + @event_fees
		
    # Calculate discounted total, if any.
		@total = @sub_total - (@discount * @sub_total)

		# Create a new receipt.
		@receipt = Receipt.new
		@receipt.credit_card_id = params[:credit_card_id]
		@receipt.total = @total
		@receipt.conference_registration_id = @conf_reg.id

		if @receipt.save
			flash[:success] = "Registration complete. Please print a copy of this receipt for your records."
			UserMailer.receipt(current_user, @receipt, @conf_reg, @event_regs).deliver_now
			@@discount = 0
			redirect_to receipt_path(@receipt.id)
		else
			flash.now[:danger] = "Duplicate registration: It looks like you've already registered for this conference."
			render 'registration_summary'
		end
    else
    	flash.now[:danger] = "Duplicate registration: It looks like you've already registered for this conference."
    	render 'registration_summary'
    end
	end

	private
	def registration_params
		params.require(:conference_registration).permit(:name, :email, :diet, :paper_id, :user_id, :conference_id, :total)
	end
end

app/views/conference_registrations/index.html.erb
<% provide(:title, "View Registrations") %>
<h1>Your conference registrations</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
   <% if !@user_registrations.empty? %>
  <table class="table table-bordered table-striped">
			<tr>
				<th>Name</th>
				<th>Conference</th>
				<th>Diet</th>
				<th>Total</th>
			</tr>
			<% @user_registrations.each do |reg| %>
			<tr>
				<td><%= reg.name %></td>
				<td><%= Conference.find_by(id: reg.conference_id).name %></td>
				
				<td><%= reg.diet %></td>
				<td><%= number_to_currency(Receipt.find_by(conference_registration_id: reg.id).total) %></td>
			</tr>
			<% end %>
		</table>
		<% else %>
      <h2>It looks like you haven't registered for any conferences...yet!</h2>
		  <p class="text-center"><%= link_to "Submit a new conference registration", select_conference_path %></p>
		<% end %>
  </div>
</div>

app/views/conference_registrations/new.html.erb
<% provide(:title, 'New Conference Registration Form') %>
<h1><%= @conference.name %><br><br>Participant Information</h1>
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= form_for @conf_reg do |reg| %>
		<%= reg.label :name %>
		<%= reg.text_field :name, required: true, placeholder: "Jane Doe"%>
		<%= reg.label :email %>
		<%= reg.text_field :email, required: true, pattern: '[^@]+@[^@]+\.[a-zA-Z]{2,6}', placeholder: "email@example.com" %>
		<%= reg.label 'Dietary preference' %>
		<%= reg.text_field :diet, required: true, placeholder: "Vegan" %>
		<%= reg.hidden_field :user_id, value: @user.id %>
		<%= reg.hidden_field :conference_id, value: @conference.id %>

		<%= form_tag new_conference_registration_path, method: :get %>
		<h1>Paper Information</h1>
    <h2>If you would like to register one of your papers, please select one from below.</h2>
    <% if !@papers.empty? %>
		<table class="table table-bordered table-striped">
			<tr>
				<th>Title</th>
				<th>Authors</th>
				<th>Select One</th>
			</tr>
			<% @papers.each do |paper| %>
			<tr>
				<td><%= paper.title %></td>
				<td><%= paper.authors %></td>
				<td><%= radio_button_tag :paper_id, paper.id %></td>
			</tr>
			<% end %>
			
		</table>
		<% else %>
    <div class="alert alert-danger center" role="alert">
				<p>It looks like you haven't added any credit cards to your profile. Please add at least one credit card in order to proceed.</p>
				 <p><%= link_to 'Upload a new paper', new_user_paper_path(@user), class: "alert-link" %></p>
				 </div>
		<% end %>
		<%= reg.submit "Next", class: "btn btn-primary"%>
		<% end %>		
	</div>
</div>

app/views/conference_registrations/registration_summary.html.erb
<% provide(:title, 'Conference Registration Form Summary') %>
<h1><%= @conference.name %><br><br>Registration Summary</h1>
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		
		<div class="panel panel-primary">
			<div class="panel-heading">
				<h3 class="panel-title">Participant Information</h3>
			</div>
			<div class="panel-body">
				<p><strong>Name:</strong> <%= @conf_reg["name"] %></p>
				<p><strong>Email:</strong> <%= @conf_reg["email"] %></p>
				<p><strong>Participant's Dietary Preference:</strong> <%= @conf_reg["diet"] %></p>
			</div>
		</div>

    <% if @paper != nil %>
			<div class="panel panel-primary">
				<div class="panel-heading">
					<h3 class="panel-title">Paper Information</h3>
				</div>
				<div class="panel-body">
					<p><strong>Title:</strong> <%= @paper.title %></p>
					<p><strong>Author(s):</strong> <%= @paper.authors %></p>
					<p><span class="label label-info">Attachment</span>
						<%= link_to @paper.title, @paper.attachment.url %>
					</p>
				</div>
			</div>
    <% end %>
    
    <% if @events != 0 %>
			<div class="panel panel-primary">
				<div class="panel-heading">
					<h3 class="panel-title">Selected Event(s) Information</h3>
				</div>
				<div class="panel-body">
					<table class="table table-bordered table-striped">
						<tr>
							<th>Name</th>
							<th>Event Type</th>
							<th>Fee</th>
						</tr>
						<% @events.each do |event| %>
						<% event = Event.find_by(id: event.to_i) %>
						<tr>
							<td><%= event.name %></td>
							<td><%= event.event_type %></td>
							<td><%= number_to_currency(event.fee) %></td>
						</tr>
						<% end %>
					</table>
				</div>
			</div>
		<% end %>

		<div class="panel panel-primary" id="update_total">
			<div class="panel-heading">
				<h3 class="panel-title">Fee Summary</h3>
			</div>
			<div class="panel-body" id="total_due">
				<table class="table table-condensed" >
					<tr>
						<td><strong>Conference Fee</strong></td>
						<td><%= number_to_currency(@fee) %></td>
					</tr>

					<% if @paper != nil %>
						<tr>
							<td><strong>Paper Fee</strong></td>
							<td><%= number_to_currency(@paper_fee) %></td>
						</tr>
					<% end %>

					<% if @events != 0 %>
						<tr>
							<td><strong>Event(s) Fee</strong></td>
							<td><%= number_to_currency(@event_fees) %></td>
						</tr>
					<% end %>

					<tr class="info">
						<td class="info"><strong>Total Due</strong></td>
						<td class="info"><%= number_to_currency(@total) %></td>
					</tr>
				</table>

				<div class="well">
					<p><strong>Participant coupon code?</strong></p>
					<%= form_for @coupon, method: :post,  url: check_coupon_code_path, remote: true do |f| %>
					  <%= f.text_field :code, :placeholder => "Enter your coupon code here" %>
					  <%= f.submit "Apply Coupon Code", class: "btn btn-info"%>
					<% end %>
					<div id="fail"></div>
				</div>

			</div>
		</div>

    <%= form_tag(controller: "conference_registrations", action: "final", method: "get") do %>
    
		<div class="panel panel-primary">
			<div class="panel-heading">
				<h3 class="panel-title">Payment Information</h3>
			</div>
			<div class="panel-body">
			  <% if !@cards.empty? %>
				<table class="table table-bordered table-striped">
					<tr>
						<th>Name</th>
						<th>Credit Card Number</th>
						<th>Card Type</th>
						<th>Select One</th>
					</tr>
					<% @cards.each do |card| %>
					<tr>
						<td><%= card.name %></td>
						<td><%= mask(card.number) %></td>
						<td><%= card.cc_type %></td>
						<td><%= radio_button_tag :credit_card_id, card.id, checked: true %></td>
					</tr>
					<% end %>
				</table>
				<% else %>
				<div class="alert alert-danger center" role="alert">
				<p>It looks like you haven't added any credit cards to your profile. Please add at least one credit card in order to proceed.</p>
				 <p><%= link_to 'Add a new credit card', new_user_credit_card_path(@user), class: "alert-link" %></p>
				 </div>
				<% end %>
			</div>
		</div>
		<%= submit_tag "Finalize registration!", class: "btn btn-primary"%>
		<% end %>
	</div>
</div>

app/views/conference_registrations/select_conference.html.erb
<% provide(:title, 'View All Conferences') %>
<h1>All conferences</h1>
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<h2>Select a conference to register for.</h2>
		<%= form_tag select_events_path, method: :get %>
		<table class="table table-bordered table-striped">
			<tr>
				<th>Conference Name</th>
				<th>Select One</th>
			</tr>
			<% @conferences.each do |conference| %>
			<% if conference.start_date.future? %>
			<tr>
				<td><%= conference.name %></td>
				<td><%= radio_button_tag :conference_id, conference.id, checked: true %></td>
			</tr>
			<% end %>
			<% end %>
		</table>
		<%= submit_tag "Next", class: "btn btn-primary" %>
	</div>
</div>

app/views/conference_registrations/select_events.html.erb
<% provide(:title, 'New Event Registration Form') %>
<h1><%= @conference.name %><br><br>Special Events</h1>
<div class="row">
	<div class="col-md-6 col-md-offset-3">
	  <h2>Please select the additional events you would like to register for.</h2>
		<%= form_tag new_conference_registration_path, method: :get %>
		<table class="table table-bordered table-striped">
			<tr>
				<th>Event Name</th>
				<th>Type</th>
				<th>Fee</th>
				<th>Select</th>
			</tr>
			<% @events.each do |event| %>
			<tr>
				<td><%= event.name %></td>
				<td><%= event.event_type %></td>
				<td><%= number_to_currency(event.fee) %></td>
				<td><%= check_box_tag "events[]", event.id %></td>
			</tr>
			<% end %>
		</table>
		<%= hidden_field_tag :conference_id, @conference.id %>
		<%= submit_tag "Next", class: "btn btn-primary" %>
	</div>
</div>