config/routes.rb
Rails.application.routes.draw do
  
  get 'coupons/generate_coupon_code'
  get 'coupons/check_coupon_code'
  post 'check_coupon_code' => 'coupons#check_coupon_code'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  resources :users do
  resources :credit_cards
  end

  resources :users do
  resources :papers
  end
  resources :papers
  resources :receipts
  resources :conferences
  resources :conference_registrations
  resources :event_registrations
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  
  get 'select-conference' => 'conference_registrations#select_conference'
  get 'select-events' => 'conference_registrations#select_events'
  get 'registration_summary' => 'conference_registrations#registration_summary'
  post 'registration_summary' => 'conference_registrations#get_discount'
  post 'registration/final' => 'conference_registrations#final'

  root             'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup'  => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get 'credit_cards/index'
  get 'credit_cards/new'
  get 'credit_cards/create'
  get 'credit_cards/edit'
  get 'credit_cards/update'
  get 'credit_cards/show'
  get 'credit_cards/destroy'
  get 'conferences/new'
  get 'conferences/create'
  get 'conferences/edit'
  get 'conferences/update'
  get 'conferences/destroy'
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<div class="container">
		<small>
			Academic Conference Registration System
		</small>
		<nav>
			<ul>
				<li><%= link_to "About",   about_path %></li>
				<li><%= link_to "Contact", contact_path %></li>
			</ul>
		</nav>
	</div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "CRS", root_path, id: "logo", class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
        <% if current_user.admin? %>
        <li class="dropdown">
         <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Account <span class="caret"></span></a>

         <ul class="dropdown-menu" role="menu">
           <li><%= link_to "Admin Dashboard", '/admin' %></li>
           <li><%= link_to "Account Settings", edit_user_path(current_user) %></li>
           <li class="divider"></li>
           <li><%= link_to "Log out", logout_path, method: "delete" %></li>
           <% else %>
           <li><%= link_to "Dashboard", current_user %></li>
           <li class="dropdown">
             <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Account <span class="caret"></span></a>

             <ul class="dropdown-menu" role="menu">
               <li><%= link_to "Account Settings", edit_user_path(current_user) %></li>
               <li class="divider"></li>
               <li><%= link_to "Log out", logout_path, method: "delete" %></li>
               <% end %>
               <% else %>
               <li><%= link_to "Log in", login_path %></li>
               <% end %>
             </ul>
           </li>
         </ul>
       </div><!-- /.navbar-collapse -->
     </div><!-- /.container-fluid -->
   </header>

app/views/layouts/_shim.html.erb
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>